In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [4]:
mortData = pd.DataFrame(pd.read_csv('../Data/mortality/2015_data.csv', sep = ','))

/Users/joeykhuang/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (40,41,42,43,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,resident_status,education_1989_revision,education_2003_revision,education_reporting_flag,month_of_death,sex,detail_age_type,detail_age,age_substitution_flag,age_recode_52,...,record_condition_18,record_condition_19,record_condition_20,race,bridged_race_flag,race_imputation_flag,race_recode_3,race_recode_5,hispanic_origin,hispanic_originrace_recode
0,1,NaN,3.0,1,1,M,1,84,NaN,42,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
1,1,NaN,6.0,1,1,M,1,70,NaN,40,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
2,1,NaN,3.0,1,1,F,1,91,NaN,44,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
3,1,NaN,3.0,1,1,F,1,40,NaN,34,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
4,1,NaN,5.0,1,1,F,1,89,NaN,43,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
5,1,NaN,6.0,1,1,M,1,78,NaN,41,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
6,1,NaN,4.0,1,1,M,1,92,NaN,44,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
7,1,NaN,3.0,1,1,M,1,82,NaN,42,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
8,1,NaN,3.0,1,1,F,1,89,NaN,43,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
9,1,NaN,9.0,1,1,F,1,93,NaN,44,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
10,1,NaN,6.0,1,1,F,1,84,NaN,42,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
11,1,NaN,3.0,1,1,F,1,84,NaN,42,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
12,1,NaN,3.0,1,1,F,1,67,NaN,39,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
13,1,NaN,6.0,1,1,M,1,94,NaN,44,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
14,1,NaN,2.0,1,1,M,1,56,NaN,37,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
15,1,NaN,3.0,1,1,M,1,32,NaN,32,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
16,1,NaN,2.0,1,1,M,1,18,NaN,29,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
17,1,NaN,3.0,1,1,M,1,48,NaN,35,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
18,1,NaN,4.0,1,1,F,1,79,NaN,41,...,NaN,NaN,NaN,3,1.0,NaN,2,3,100,8
19,1,NaN,6.0,1,1,M,1,85,NaN,43,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
20,1,NaN,6.0,1,1,F,1,61,NaN,38,...,NaN,NaN,NaN,1,1.0,NaN,1,1,100,6
21,1,NaN,3.0,1,1,M,1,56,NaN,37,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
22,1,NaN,4.0,1,1,M,1,72,NaN,40,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
23,1,NaN,6.0,1,1,F,1,86,NaN,43,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
24,1,NaN,9.0,1,1,M,1,98,NaN,45,...,NaN,NaN,NaN,7,NaN,NaN,2,4,100,8
25,1,NaN,4.0,1,1,F,1,66,NaN,39,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
26,1,NaN,3.0,1,1,F,1,62,NaN,38,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
27,1,NaN,1.0,1,1,F,1,82,NaN,42,...,NaN,NaN,NaN,3,NaN,NaN,2,3,100,8
28,1,NaN,2.0,1,1,M,1,60,NaN,38,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
29,1,NaN,4.0,1,1,F,1,43,NaN,34,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2718168,1,NaN,2.0,1,12,M,1,67,NaN,39,...,NaN,NaN,NaN,2,NaN,NaN,3,2,998,9
2718169,1,NaN,1.0,1,12,F,1,63,NaN,38,...,NaN,NaN,NaN,4,NaN,NaN,2,4,100,8
2718170,1,NaN,4.0,1,12,F,1,78,NaN,41,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718171,1,NaN,9.0,1,12,M,1,56,NaN,37,...,NaN,NaN,NaN,28,NaN,NaN,2,4,100,8
2718172,1,NaN,2.0,1,12,F,1,88,NaN,43,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718173,1,NaN,1.0,1,12,M,1,81,NaN,42,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718174,1,NaN,5.0,1,12,F,1,73,NaN,40,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718175,2,NaN,1.0,1,12,M,5,8,NaN,2,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
2718176,1,NaN,9.0,1,12,F,1,58,NaN,37,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718177,1,NaN,1.0,1,12,F,5,2,NaN,2,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718178,2,NaN,1.0,1,12,M,4,8,NaN,9,...,NaN,NaN,NaN,2,NaN,1.0,3,2,998,9
2718179,1,NaN,3.0,1,12,M,1,64,NaN,38,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718180,1,NaN,9.0,1,1,M,1,87,NaN,43,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718181,1,NaN,2.0,1,12,M,1,65,NaN,39,...,NaN,NaN,NaN,2,NaN,NaN,3,2,998,9
2718182,1,NaN,9.0,1,6,M,1,68,NaN,39,...,NaN,NaN,NaN,2,NaN,NaN,3,2,299,5
2718183,1,NaN,1.0,1,12,M,1,68,NaN,39,...,NaN,NaN,NaN,1,NaN,NaN,1,1,260,2
2718184,1,NaN,1.0,1,12,M,4,2,NaN,4,...,NaN,NaN,NaN,2,NaN,1.0,3,2,998,9
2718185,1,NaN,1.0,1,10,M,5,1,NaN,2,...,NaN,NaN,NaN,1,NaN,NaN,1,1,275,5
2718186,3,NaN,7.0,1,12,M,1,84,NaN,42,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
2718187,1,NaN,9.0,1,12,M,1,86,NaN,43,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
2718188,1,NaN,6.0,1,12,M,1,65,NaN,39,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718189,1,NaN,1.0,1,12,M,6,5,NaN,1,...,NaN,NaN,NaN,1,NaN,NaN,1,1,998,9
2718190,1,NaN,9.0,1,11,F,1,39,NaN,33,...,NaN,NaN,NaN,2,NaN,NaN,3,2,998,9
2718191,1,NaN,9.0,1,10,F,1,53,NaN,36,...,NaN,NaN,NaN,2,NaN,1.0,3,2,998,9
2718192,1,NaN,9.0,1,10,F,1,46,NaN,35,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718193,1,NaN,1.0,1,5,M,6,5,NaN,1,...,NaN,NaN,NaN,2,NaN,1.0,3,2,998,9
2718194,1,NaN,9.0,1,12,F,1,48,NaN,35,...,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
2718195,4,NaN,9.0,1,12,M,1,33,NaN,32,...,NaN,NaN,NaN,1,NaN,1.0,1,1,299,5
2718196,4,NaN,9.0,1,7,M,1,83,NaN,42,...,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7
2718197,1,NaN,9.0,1,12,M,1,81,NaN,42,...,NaN,NaN,NaN,2,NaN,NaN,3,2,998,9